# Generated by Django 5.2.5 on 2025-08-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_iconcolor_role_teamsection_brand_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Heading (e.g. Our Address, Call Us)', max_length=100)),
                ('description', models.TextField(help_text='Details like address, phone number, email etc.')),
                ('icon_class', models.CharField(choices=[('bi bi-geo-alt', 'Address'), ('bi bi-telephone', 'Phone'), ('bi bi-envelope', 'Email'), ('bi bi-clock', 'Timing')], default='bi bi-geo-alt', help_text='Bootstrap icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorting order')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.iconcolor')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
