# Generated by Django 5.2.5 on 2025-08-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamSection',
            new_name='SectionTitle',
        ),
    ]
