# Generated by Django 5.2.5 on 2025-08-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_teamsection_sectiontitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontitle',
            name='color_class',
            field=models.CharField(blank=True, default='', help_text='Bootstrap color class (e.g. text-primary, text-success).', max_length=50),
        ),
        migrations.AddField(
            model_name='sectiontitle',
            name='icon_class',
            field=models.CharField(blank=True, default='', help_text='Bootstrap icon class (e.g. bi bi-people).', max_length=50),
        ),
    ]
