# Generated by Django 5.2.5 on 2025-08-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sectiontitle_color_class_sectiontitle_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontitle',
            name='section_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='sectiontitle',
            name='heading',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='sectiontitle',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
