# Generated by Django 5.2.5 on 2025-08-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sectiontitle_section_name_alter_sectiontitle_heading_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionTitle',
        ),
    ]
