# Generated by Django 5.2.5 on 2025-08-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_sectiontitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default='', max_length=120)),
                ('heading', models.CharField(default='', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('color_class', models.CharField(blank=True, default='', help_text='Bootstrap color class (e.g. text-primary, text-success).', max_length=50)),
                ('icon_class', models.CharField(blank=True, default='', help_text='Bootstrap icon class (e.g. bi bi-people).', max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Title — Section',
                'verbose_name_plural': 'Title — Sections',
            },
        ),
    ]
