# Generated by Django 5.2.5 on 2025-08-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_titlesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='titlesection',
            options={'verbose_name': 'Title — Section', 'verbose_name_plural': 'Title  Sections'},
        ),
        migrations.AlterField(
            model_name='herosection',
            name='bg_gradient_from',
            field=models.CharField(default='#8e2de2', max_length=20),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='bg_gradient_to',
            field=models.CharField(default='#4a00e0', max_length=20),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('blog', 'Blog'), ('shop', 'Shop'), ('contact', 'Contact'), ('faq', 'FAQ'), ('privacy', 'Privacy & Policy'), ('terms', 'Terms & Conditions'), ('combo list', 'Combo List'), ('category list', 'Category List')], default='home', max_length=32),
        ),
    ]
