# Generated by Django 5.2.5 on 2025-08-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_feedback_alter_titlesection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='email_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='github_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='whatsapp_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='website_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
