# Generated by Django 5.2.5 on 2025-08-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_teammember_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique ID, e.g. 'what-we-collect'", unique=True)),
                ('icon', models.CharField(blank=True, help_text="Bootstrap icon class, e.g. 'bi bi-card-list'", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TermsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique ID for section, e.g. 'agreement'", unique=True)),
                ('icon', models.CharField(blank=True, help_text="Bootstrap icon class, e.g. 'bi bi-patch-check-fill'", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
